
export let questionBank = [
    [
        {
            topic:"什么可进行资源再利用?",
            options:[
                {
                    title:"A",
                    content:"可回收物"
                },
                {
                    title:"B",
                    content:"其他垃圾"
                },
                {
                    title:"C",
                    content:"有害垃圾"
                },
                {
                    title:"D",
                    content:"厨余垃圾"
                },
            ],
            answer:
            {
                title:"A",
                content:"可回收物"
            },
        },
        {
            topic:"下面属于其他垃圾的是?",
            options:[
                {
                    title:"A",
                    content:"杀虫剂"
                },
                {
                    title:"B",
                    content:"用过的湿纸巾"
                },
                {
                    title:"C",
                    content:"贝壳"
                },
                {
                    title:"D",
                    content:"可乐罐"
                },
            ],
            answer: {
                title:"B",
                content:"用过的湿纸巾"
            },
        },
        {
            topic:"有机玻璃制品属于什么?",
            options:[
                {
                    title:"A",
                    content:"可回收物"
                },
                {
                    title:"B",
                    content:"其他垃圾"
                },
                {
                    title:"C",
                    content:"有害垃圾"
                },
                {
                    title:"D",
                    content:"厨余垃圾"
                },
            ],
            answer:{
                title:"A",
                content:"可回收物"
            },
        },
        {
            topic:"用过的卫生纸属于什么垃圾?",
            options:[
                {
                    title:"A",
                    content:"可回收物"
                },
                {
                    title:"B",
                    content:"其他垃圾"
                },
                {
                    title:"C",
                    content:"有害垃圾"
                },
                {
                    title:"D",
                    content:"厨余垃圾"
                },
            ],
            answer:{
                title:"B",
                content:"其他垃圾"
            },
        },
        {
            topic:"猫砂属于什么垃圾?",
            options:[
                {
                    title:"A",
                    content:"可回收物"
                },
                {
                    title:"B",
                    content:"其他垃圾"
                },
                {
                    title:"C",
                    content:"有害垃圾"
                },
                {
                    title:"D",
                    content:"厨余垃圾"
                },
            ],
            answer:{
                title:"B",
                content:"其他垃圾"
            },
        },
        {
            topic:"一次性牙刷纸属于什么垃圾?",
            options:[
                {
                    title:"A",
                    content:"可回收物"
                },
                {
                    title:"B",
                    content:"其他垃圾"
                },
                {
                    title:"C",
                    content:"有害垃圾"
                },
                {
                    title:"D",
                    content:"厨余垃圾"
                },
            ],
            answer:{
                title:"A",
                content:"可回收物"
            },
        },
        {
            topic:"下面不属于厨余垃圾的是?",
            options:[
                {
                    title:"A",
                    content:"贝壳"
                },
                {
                    title:"B",
                    content:"骨头"
                },
                {
                    title:"C",
                    content:"蔬菜"
                },
                {
                    title:"D",
                    content:"塑料文具"
                },
            ],
            answer:{
                title:"D",
                content:"塑料文具"
            },
        },
        {
            topic:"下面属于不可回收物的是?",
            options:[
                {
                    title:"A",
                    content:"玻璃啤酒瓶"
                },
                {
                    title:"B",
                    content:"海绵"
                },
                {
                    title:"C",
                    content:"衣服"
                },
                {
                    title:"D",
                    content:"袜子"
                },
            ],
            answer:{
                title:"B",
                content:"海绵"
            },
        },
        {
            topic:"杂志属于什么?",
            options:[
                {
                    title:"A",
                    content:"厨余垃圾"
                },
                {
                    title:"B",
                    content:"其他垃圾"
                },
                {
                    title:"C",
                    content:"有害垃圾"
                },
                {
                    title:"D",
                    content:"可回收垃圾"
                },
            ],
            answer:{
                title:"D",
                content:"可回收垃圾"
            },
        },
        {
            topic:"旧衣服属于什么?",
            options:[
                {
                    title:"A",
                    content:"可回收物"
                },
                {
                    title:"B",
                    content:"其他垃圾"
                },
                {
                    title:"C",
                    content:"有害垃圾"
                },
                {
                    title:"D",
                    content:"厨余垃圾"
                },
            ],
            answer:{
                title:"A",
                content:"可回收物"
            },
        },
        {
            topic:"废手机充电电池属于什么?",
            options:[
                {
                    title:"A",
                    content:"可回收物"
                },
                {
                    title:"B",
                    content:"其他垃圾"
                },
                {
                    title:"C",
                    content:"有害垃圾"
                },
                {
                    title:"D",
                    content:"厨余垃圾"
                },
            ],
            answer:{
                title:"C",
                content:"有害垃圾"
            },
        },
        {
            topic:"下面不属于可回收物的是?",
            options:[
                {
                    title:"A",
                    content:"旧报纸"
                },
                {
                    title:"B",
                    content:"金属"
                },
                {
                    title:"C",
                    content:"塑料"
                },
                {
                    title:"D",
                    content:"烟头"
                },
            ],
            answer:{
                title:"D",
                content:"烟头"
            },
        },
    ],

    [
        {
            topic:"废旧荧光灯属于什么?",
            options:[
                {
                    title:"A",
                    content:"可回收物"
                },
                {
                    title:"B",
                    content:"其他垃圾"
                },
                {
                    title:"C",
                    content:"有害垃圾"
                },
                {
                    title:"D",
                    content:"厨余垃圾"
                },
            ],
            answer:{
                title:"C",
                content:"有害垃圾"
            },
        },
        {
            topic:"什么垃圾可进行降解堆肥处理?",
            options:[
                {
                    title:"A",
                    content:"可回收物"
                },
                {
                    title:"B",
                    content:"其他垃圾"
                },
                {
                    title:"C",
                    content:"有害垃圾"
                },
                {
                    title:"D",
                    content:"厨余垃圾"
                },
            ],
            answer:{
                title:"D",
                content:"厨余垃圾"
            },
        },
        {
            topic:"目前城市垃圾处理主要方式不包括哪种?",
            options:[
                {
                    title:"A",
                    content:"焚烧"
                },
                {
                    title:"B",
                    content:"堆肥"
                },
                {
                    title:"C",
                    content:"填埋"
                },
                {
                    title:"D",
                    content:"简单堆积"
                },
            ],
            answer:{
                title:"D",
                content:"简单堆积"
            },
        },
        {
            topic:"保鲜膜属于什么垃圾?",
            options:[
                {
                    title:"A",
                    content:"可回收物"
                },
                {
                    title:"B",
                    content:"其他垃圾"
                },
                {
                    title:"C",
                    content:"有害垃圾"
                },
                {
                    title:"D",
                    content:"厨余垃圾"
                },
            ],
            answer:{
                title:"A",
                content:"可回收物"
            },
        },
        {
            topic:"一次性纸杯属于什么?",
            options:[
                {
                    title:"A",
                    content:"可回收物"
                },
                {
                    title:"B",
                    content:"其他垃圾"
                },
                {
                    title:"C",
                    content:"有害垃圾"
                },
                {
                    title:"D",
                    content:"厨余垃圾"
                },
            ],
            answer:{
                title:"A",
                content:"可回收物"
            },
        },
        {
            topic:"保鲜袋属于什么?",
            options:[
                {
                    title:"A",
                    content:"厨余垃圾"
                },
                {
                    title:"B",
                    content:"其他垃圾"
                },
                {
                    title:"C",
                    content:"有害垃圾"
                },
                {
                    title:"D",
                    content:"可回收垃圾"
                },
            ],
            answer:{
                title:"B",
                content:"其他垃圾"
            },
        },
        {
            topic:"废电池乱丢对人体可能造成?",
            options:[
                {
                    title:"A",
                    content:"镉中毒"
                },
                {
                    title:"B",
                    content:"氰中毒"
                },
                {
                    title:"C",
                    content:"铅中毒"
                },
                {
                    title:"D",
                    content:"氟中毒"
                },
            ],
            answer:{
                title:"A",
                content:"镉中毒"
            },
        },
        {
            topic:"过期食品属于什么?",
            options:[
                {
                    title:"A",
                    content:"可回收物"
                },
                {
                    title:"B",
                    content:"其他垃圾"
                },
                {
                    title:"C",
                    content:"有害垃圾"
                },
                {
                    title:"D",
                    content:"厨余垃圾"
                },
            ],
            answer:{
                title:"D",
                content:"厨余垃圾"
            },
        },
        {
            topic:"有机玻璃制品属于?",
            options:[
                {
                    title:"A",
                    content:"可回收物"
                },
                {
                    title:"B",
                    content:"其他垃圾"
                },
                {
                    title:"C",
                    content:"有害垃圾"
                },
                {
                    title:"D",
                    content:"厨余垃圾"
                },
            ],
            answer:{
                title:"A",
                content:"可回收物"
            },
        },
    ],

    [
        {
            topic:"旅行袋是属于?",
            options:[
                {
                    title:"A",
                    content:"可回收物"
                },
                {
                    title:"B",
                    content:"其他垃圾"
                },
                {
                    title:"C",
                    content:"有害垃圾"
                },
                {
                    title:"D",
                    content:"厨余垃圾"
                },
            ],
            answer:{
                title:"B",
                content:"其他垃圾"
            },
        },
        {
            topic:"下列哪组均属于其他垃圾?",
            options:[
                {
                    title:"A",
                    content:"鸡蛋壳、普通玻璃"
                },
                {
                    title:"B",
                    content:"玉米核、塑料餐盒"
                },
                {
                    title:"C",
                    content:"餐巾纸、厕纸"
                },
                {
                    title:"D",
                    content:"金属厨具、塑料玩具"
                },
            ],
            answer:{
                title:"C",
                content:"餐巾纸、厕纸"
            },
        },
        {
            topic:"安全帽是属于什么垃圾?",
            options:[
                {
                    title:"A",
                    content:"可回收物"
                },
                {
                    title:"B",
                    content:"其他垃圾"
                },
                {
                    title:"C",
                    content:"有害垃圾"
                },
                {
                    title:"D",
                    content:"厨余垃圾"
                },
            ],
            answer:{
                title:"B",
                content:"其他垃圾"
            },
        },
        {
            topic:"下面什么垃圾是可回收垃圾?",
            options:[
                {
                    title:"A",
                    content:"饮料等纸包装盒"
                },
                {
                    title:"B",
                    content:"废纸、烟头"
                },
                {
                    title:"C",
                    content:"废纸、树叶"
                },
                {
                    title:"D",
                    content:"陶器、花盘"
                },
            ],
            answer:{
                title:"A",
                content:"饮料等纸包装盒"
            },
        },
        {
            topic:"下列哪组均属于可回收物?",
            options:[
                {
                    title:"A",
                    content:"灰土、毛巾"
                },
                {
                    title:"B",
                    content:"纸杯、空调、瓷器"
                },
                {
                    title:"C",
                    content:"过期药品、烟头"
                },
                {
                    title:"D",
                    content:"玻璃杯、电脑"
                },
            ],
            answer:{
                title:"D",
                content:"玻璃杯、电脑"
            },
        },
        {
            topic:"下列垃圾哪些属于其他垃圾?",
            options:[
                {
                    title:"A",
                    content:"纸尿裤、烟头"
                },
                {
                    title:"B",
                    content:"玻璃瓶、玻璃杯"
                },
                {
                    title:"C",
                    content:"月历、纸箱"
                },
                {
                    title:"D",
                    content:"茶叶渣贝壳"
                },
            ],
            answer:{
                title:"A",
                content:"纸尿裤、烟头"
            },
        },
        {
            topic:"水果拼盘属于哪一类垃圾?",
            options:[
                {
                    title:"A",
                    content:"其他垃圾"
                },
                {
                    title:"B",
                    content:"厨余垃圾"
                },
                {
                    title:"C",
                    content:"可回收物"
                },
                {
                    title:"D",
                    content:"有害垃圾"
                },
            ],
            answer:{
                title:"B",
                content:"厨余垃圾"
            },
        },
        {
            topic:"水银温度计属于什么?",
            options:[
                {
                    title:"A",
                    content:"可回收物"
                },
                {
                    title:"B",
                    content:"其他垃圾"
                },
                {
                    title:"C",
                    content:"有害垃圾"
                },
                {
                    title:"D",
                    content:"厨余垃圾"
                },
            ],
            answer:{
                title:"C",
                content:"有害垃圾"
            },
        },
        {
            topic:"撕掉了的旧照片，应该丢到哪个垃圾桶内?",
            options:[
                {
                    title:"A",
                    content:"可回收物"
                },
                {
                    title:"B",
                    content:"其他垃圾"
                },
                {
                    title:"C",
                    content:"有害垃圾"
                },
                {
                    title:"D",
                    content:"厨余垃圾"
                },
            ],
            answer:{
                title:"C",
                content:"有害垃圾"
            },
        },
    ],

    [
        {
            topic:"塑料筷子属于哪类垃圾?",
            options:[
                {
                    title:"A",
                    content:"其他垃圾"
                },
                {
                    title:"B",
                    content:"厨余垃圾"
                },
                {
                    title:"C",
                    content:"可回收物"
                },
                {
                    title:"D",
                    content:"有害垃圾"
                },
            ],
            answer:{
                title:"C",
                content:"可回收物"
            },
        },
        {
            topic:"塑料玩具属于什么垃圾?",
            options:[
                {
                    title:"A",
                    content:"其他垃圾"
                },
                {
                    title:"B",
                    content:"厨余垃圾"
                },
                {
                    title:"C",
                    content:"可回收物"
                },
                {
                    title:"D",
                    content:"有害垃圾"
                },
            ],
            answer:{
                title:"C",
                content:"可回收物"
            },
        },
        {
            topic:"糖果包装纸属于什么垃圾?",
            options:[
                {
                    title:"A",
                    content:"其他垃圾"
                },
                {
                    title:"B",
                    content:"厨余垃圾"
                },
                {
                    title:"C",
                    content:"可回收物"
                },
                {
                    title:"D",
                    content:"有害垃圾"
                },
            ],
            answer:{
                title:"A",
                content:"其他垃圾"
            },
        },
        {
            topic:"西瓜籽属于哪类垃圾?",
            options:[
                {
                    title:"A",
                    content:"其他垃圾"
                },
                {
                    title:"B",
                    content:"厨余垃圾"
                },
                {
                    title:"C",
                    content:"可回收物"
                },
                {
                    title:"D",
                    content:"有害垃圾"
                },
            ],
            answer:{
                title:"B",
                content:"厨余垃圾"
            },
        },
        {
            topic:"洗甲水属于哪一类垃圾?",
            options:[
                {
                    title:"A",
                    content:"其他垃圾"
                },
                {
                    title:"B",
                    content:"厨余垃圾"
                },
                {
                    title:"C",
                    content:"可回收物"
                },
                {
                    title:"D",
                    content:"有害垃圾"
                },
            ],
            answer:{
                title:"D",
                content:"有害垃圾"
            },
        },
        {
            topic:"下面属于可回收物的是?",
            options:[
                {
                    title:"A",
                    content:"橡胶轮胎"
                },
                {
                    title:"B",
                    content:"荧光灯管"
                },
                {
                    title:"C",
                    content:"陶瓷"
                },
                {
                    title:"D",
                    content:"金属油漆桶"
                },
            ],
            answer:{
                title:"A",
                content:"橡胶轮胎"
            },
        },
        {
            topic:"牛奶等食品利乐包装盒属于什么?",
            options:[
                {
                    title:"A",
                    content:"可焚烧垃圾"
                },
                {
                    title:"B",
                    content:"其他垃圾"
                },
                {
                    title:"C",
                    content:"可回收物"
                },
                {
                    title:"D",
                    content:"厨余垃圾"
                },
            ],
            answer:{
                title:"C",
                content:"可回收物"
            },
        },
        {
            topic:"农贸市场垃圾主要成分属于什么?",
            options:[
                {
                    title:"A",
                    content:"其他垃圾"
                },
                {
                    title:"B",
                    content:"厨余垃圾"
                },
                {
                    title:"C",
                    content:"可回收物"
                },
                {
                    title:"D",
                    content:"有害垃圾"
                },
            ],
            answer:{
                title:"B",
                content:"厨余垃圾"
            },
        },
        {
            topic:"下面哪个不是有害垃圾?",
            options:[
                {
                    title:"A",
                    content:"碎玻璃片"
                },
                {
                    title:"B",
                    content:"过期药品"
                },
                {
                    title:"C",
                    content:"废水银温度计"
                },
                {
                    title:"D",
                    content:"废电池"
                },
            ],
            answer:{
                title:"A",
                content:"碎玻璃片"
            },
        },
        {
            topic:"墨盒属于什么垃圾?",
            options:[
                {
                    title:"A",
                    content:"其他垃圾"
                },
                {
                    title:"B",
                    content:"厨余垃圾"
                },
                {
                    title:"C",
                    content:"可回收物"
                },
                {
                    title:"D",
                    content:"有害垃圾"
                },
            ],
            answer:{
                title:"D",
                content:"有害垃圾"
            },
        },
    ],

    [
        {
            topic:"下面不属于可回收物的是?",
            options:[
                {
                    title:"A",
                    content:"笔记本"
                },
                {
                    title:"B",
                    content:"复印纸"
                },
                {
                    title:"C",
                    content:"玻璃瓶"
                },
                {
                    title:"D",
                    content:"烟头"
                },
            ],
            answer:{
                title:"D",
                content:"烟头"
            },
        },
        {
            topic:"下列哪个不属于厨余垃圾?",
            options:[
                {
                    title:"A",
                    content:"过期食品"
                },
                {
                    title:"B",
                    content:"剩饭剩菜"
                },
                {
                    title:"C",
                    content:"鱼刺和骨头"
                },
                {
                    title:"D",
                    content:"废弃的金属勺子"
                },
            ],
            answer:{
                title:"D",
                content:"废弃的金属勺子"
            },
        },
        {
            topic:"大块的骨头应归类到哪些垃圾?",
            options:[
                {
                    title:"A",
                    content:"其他垃圾"
                },
                {
                    title:"B",
                    content:"厨余垃圾"
                },
                {
                    title:"C",
                    content:"可回收物"
                },
                {
                    title:"D",
                    content:"有害垃圾"
                },
            ],
            answer:{
                title:"B",
                content:"厨余垃圾"
            },
        },
        {
            topic:"哪种垃圾可以重新提炼出有用的材料?",
            options:[
                {
                    title:"A",
                    content:"其他垃圾"
                },
                {
                    title:"B",
                    content:"厨余垃圾"
                },
                {
                    title:"C",
                    content:"可回收物"
                },
                {
                    title:"D",
                    content:"有害垃圾"
                },
            ],
            answer:{
                title:"C",
                content:"可回收物"
            },
        },
        {
            topic:"易拉罐应放入哪类垃圾桶内?",
            options:[
                {
                    title:"A",
                    content:"其他垃圾"
                },
                {
                    title:"B",
                    content:"厨余垃圾"
                },
                {
                    title:"C",
                    content:"可回收物"
                },
                {
                    title:"D",
                    content:"有害垃圾"
                },
            ],
            answer:{
                title:"C",
                content:"可回收物"
            },
        },
        {
            topic:"草稿纸应放入哪类垃圾桶?",
            options:[
                {
                    title:"A",
                    content:"厨余垃圾"
                },
                {
                    title:"B",
                    content:"可回收垃圾"
                },
                {
                    title:"C",
                    content:"有害垃圾"
                },
                {
                    title:"D",
                    content:"其他垃圾"
                },
            ],
            answer:{
                title:"B",
                content:"可回收垃圾"
            },
        },
        {
            topic:"橘子皮、苹果核应放入哪类垃圾桶?",
            options:[
                {
                    title:"A",
                    content:"可回收垃圾"
                },
                {
                    title:"B",
                    content:"其他垃圾"
                },
                {
                    title:"C",
                    content:"可回收物"
                },
                {
                    title:"D",
                    content:"厨余垃圾"
                },
            ],
            answer:{
                title:"D",
                content:"厨余垃圾"
            },
        },
        {
            topic:"以下哪种垃圾最不易降解?",
            options:[
                {
                    title:"A",
                    content:"纸张"
                },
                {
                    title:"B",
                    content:"玻璃瓶"
                },
                {
                    title:"C",
                    content:"塑料袋"
                },
                {
                    title:"D",
                    content:"瓜果皮"
                },
            ],
            answer:{
                title:"B",
                content:"玻璃瓶"
            },
        },
        {
            topic:"生活垃圾分类的意义?",
            options:[
                {
                    title:"A",
                    content:"促进资源回收利用"
                },
                {
                    title:"B",
                    content:"促进绿色发展"
                },
                {
                    title:"C",
                    content:"优化人居环境"
                },
                {
                    title:"D",
                    content:"以上都是"
                },
            ],
            answer:{
                title:"D",
                content:"以上都是"
            },
        },
        {
            topic:"废手机等电子产品属于?",
            options:[
                {
                    title:"A",
                    content:"其他垃圾"
                },
                {
                    title:"B",
                    content:"厨余垃圾"
                },
                {
                    title:"C",
                    content:"可回收物"
                },
                {
                    title:"D",
                    content:"有害垃圾"
                },
            ],
            answer:{
                title:"C",
                content:"可回收物"
            },
        },
    ],

    [
        {
            topic:"被油污染了的旧报纸是否是可回收物?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
        {
            topic:"废荧光等管是否是有害垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"海绵是否是可回收物?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
        {
            topic:"旧鞋子属于可回收物?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"家庭用的沐浴露洗发水的塑料瓶是属于可回收物?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"泡沫是否属于可回收物?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"废扣子电池属于有害垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"废旧的球类属于其他垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"卫生巾和纸尿裤属于可回收物?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
        {
            topic:"废旧雨伞属于可回收物吗",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
    ],

    [
        {
            topic:"家庭日常生活中打碎的陶瓷碗碟属于可回收物?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
        {
            topic:"报纸、纸皮属于可回收物?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"瓜果皮核、菜根菜头属于其他垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
        {
            topic:"鸡、鸭、鱼等动物废弃内脏属于其他垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
        {
            topic:"牛奶盒以及饮料盒也叫利乐包，利乐、包属于可回收物?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"家庭枯萎的水培植物和鲜花属于其他垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
        {
            topic:"消毒剂及其包装物属于有害垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"被污染的塑料袋清洗干净后是否属于可回收物?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"废旧的被子、床单属于可回收物?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"废温度计属于有害垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
    ],

    [
        {
            topic:"有机玻璃制品属于其他垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
        {
            topic:"废弃的卫生纸属于可回收物?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
        {
            topic:"油漆桶属于可回收物?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
        {
            topic:"废弃的树叶属于可回收垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
        {
            topic:"废旧的收音机属于有害垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
        {
            topic:"涂有油漆的废玻璃和金属属于可回收物?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
        {
            topic:"过期的药品属于有害垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"消毒剂及其包装物属于有害垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"一次性纸杯是属于可回收物?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
        {
            topic:"旧陶瓷罐是属于可回收物?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
    ],

    [
        {
            topic:"矿泉水瓶属于可回收物?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"废塑料属于其他垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
        {
            topic:"脏污的卫生巾属于可回收物?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
        {
            topic:"用过的手电筒电池属于有害垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"打碎的陶瓷碗碟属于可回收物?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
        {
            topic:"家庭中的杀虫剂和蚊香属于有害垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"家庭废旧的地毯和踏垫属于可回收垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"废化妆品及其包装物属于有害垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"可回收垃圾，包括生活垃圾中未污染的适宜回收和资源利用的垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"混杂、污染、难分类的塑料类、玻璃类、纸类等生活垃圾属于可回收垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
    ],

    [
        {
            topic:"方便面盒属于可回收垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"废旧的收音机和手电筒属于可回收垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"未被污染的塑料餐具属于可回收垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"其他垃圾可进行资源再利用?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
        {
            topic:"安全帽属于其他垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"旅行袋属于可回收物?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"毛巾属于可回收物?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"塑料玩具属于其他垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
        {
            topic:"旧照片属于有害垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"A",
                content:"是"
            },
        },
        {
            topic:"鸡蛋壳属于其他垃圾?",
            options:[
                {
                    title:"A",
                    content:"是"
                },
                {
                    title:"B",
                    content:"否"
                },
            ],
            answer:{
                title:"B",
                content:"否"
            },
        },
    ],
] 